docker:
  image: g4s8/rultor:alpine3.10
architect:
  - vssekorin
assets:
  settings.xml: vssekorin/home#assets/cactoos/settings.xml
  pubring.gpg: vssekorin/home#assets/pubring.gpg
  secring.gpg: vssekorin/home#assets/secring.gpg
merge:
  script: |
    pdd -f /dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
deploy:
  script: |
    pdd -f /dev/null
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  sensitive:
    - settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    gpg --import /home/r/pubring.gpg
    gpg --allow-secret-key-import --no-tty --batch --import /home/r/secring.gpg
    mvn versions:set "-DnewVersion=${tag}" --settings ../settings.xml
    git commit -am "${tag}"
    # note: -Pcactoos is needed to have the gpg and sonar secrets injected
    # Sonar is disabled (was -Psonar) because sonarcloud.io only support Java 11+
    mvn clean deploy -Pcactoos -Pqulice -Psonatype --errors --settings ../settings.xml
